# Generated by Django 6.0.5 on 2026-06-24 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_orders', to='shipment.shipment'),
        ),
    ]
